<!DOCTYPE html>
<?php 
session_start();
?>
<html lang="cs-cz">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/jpg" href="img/mcu.ico" />
    <link rel="stylesheet" href="style/fotogalerie.css">
    <link rel="stylesheet" href="style/header.css">
    <title>FOTOGALERIE</title>
</head>

<body>
    <?php require ("./view/header.phtml");?>
    <h1>Filmy</h1>
    <div class="filmy">
        <h2><b>Avengers 1-4</b></h2>
        <div class="avengers">
            <div class="av12">
                <div class="cards">
                    <div class="container">
                        <h3>Marvel's The Avengers</h3>
                    </div>
                    <img src="img/a1_poster.jpg" alt="plakát pro první film Avengers">
                </div>
                <div class="cards">
                    <div class="container">
                        <h3>Avengers: Age of Ultron</h3>
                    </div>
                    <img src="img/a2_poster.jpg" alt="plakát pro druhý film Avengers">
                </div>
            </div>
            <div class="av34">
                <div class="cards">
                    <div class="container">
                        <h3>Avengers: Infinity War</h3>
                    </div>
                    <img src="img/a3_poster.jpg" alt="plakát pro třetí film Avengers">
                </div>
                <div class="cards">
                    <div class="container">
                        <h3>Avengers: Endgame</h3>
                    </div>
                    <img src="img/a4_poster.jpg" alt="plakát pro čtvrtý film Avengers">
                </div>
            </div>
        </div>
        <h2><b>Iron Man 1-3</b></h2>
        <div class="ironman">
            <div class="card">
                <div class="container">
                    <h3>Iron Man</h3>
                </div>
                <img src="img/i1_poster.jpg" alt="plakát pro film Iron Man 1">
            </div>
            <div class="card">
                <div class="container">
                    <h3>Iron Man 2</h3>
                </div>
                <img src="img/i2_poster.jpg" alt="plakát pro film Iron Man 2">
            </div>
            <div class="card">
                <div class="container">
                    <h3>Iron Man 3</h3>
                </div>
                <img src="img/i3_poster.jpg" alt="plakát pro film Iron Man 3">
            </div>
        </div>
        <h2><b>Captain America 1-3</b></h2>
        <div class="camerica">
            <div class="card">
                <div class="container">
                    <h3>Captain America: The First Avenger</h3>
                </div>
                <img src="img/c1_poster.jpg" alt="plakát pro Captain America: The First Avenger">
            </div>
            <div class="card">
                <div class="container">
                    <h3>Captain America: The Winter Soldier</h3>
                </div>
                <img src="img/c2_poster.jpg" alt="plakát pro Captain America: The Winter Soldier">
            </div>
            <div class="card">
                <div class="container">
                    <h3>Captain America: Civil War</h3>
                </div>
                <img src="img/c3_poster.jpg" alt="plakát pro Captain America: Civil War">
            </div>
        </div>
        <h2><b>Thor 1-3</b></h2>
        <div class="thor">
            <div class="card">
                <div class="container">
                    <h3>Thor</h3>
                </div>
                <img src="img/t1_poster.jpg" alt="plakát pro film Thor">
            </div>
            <div class="card">
                <div class="container">
                    <h3>Thor: The Dark World</h3>
                </div>
                <img src="img/t2_poster.jpg" alt="plakát pro film Thor: The Dark World">
            </div>
            <div class="card">
                <div class="container">
                    <h3>Thor: Ragnarok</h3>
                </div>
                <img src="img/t3_poster.jpg" alt="plakát pro film Thor: Ragnarok">
            </div>
        </div>
    </div>
    <h1>Seriály</h1>
    <div class="serialy">
        <div class="serial">
            <div class="cards">
                <div class="container">
                    <h3>Falcon and The Winter Soldier</h3>
                </div>
                <img src="img/fatws_poster.jpg" alt="plakát pro Falcon and The Winter Soldier">
            </div>
            <div class="cards">
                <div class="container">
                    <h3>WandaVision</h3>
                </div>
                <img src="img/wv_poster.jpg" alt="plakát pro WandaVision">
            </div>
        </div>
    </div>
    <footer>
        <ul class="odkaz">
            <li>Matěj Bartusek, m.bartusek.st@spseiostrava<a href="img/tf.jpg" target="_blank">.</a>cz, 13. 6. 2022</li>
        </ul>
        <ul class="odkaz">
            <li><a href="#top">ZPÁTKY NAHORU</a></li>
        </ul>
    </footer>
</body>

</html>