<!DOCTYPE html>
<?php 
session_start();
?>
<html lang="cs-cz">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/jpg" href="img/mcu.ico" />
    <link rel="stylesheet" href="style/style.css">
    <link rel="stylesheet" href="style/header.css">
    <title>MCU</title>
</head>

<body>
    <?php require("./view/header.phtml");?>
    <h2>Marvel Studios</h2>
    <p>Marvel Studios je americké filmové studio, které odstartovalo v roce 2008 filmem <i>Iron Man</i>. <br>Studiu
        hrozil krach a všechno záviselo právě na snímku Iron Man. <br>Dnes je Marvel Studios vlastněno Disney a je jedno
        z nejvýdělečnějších studií.</p>
    <h3>Prezident</h3>
    <p>Kevin Feige</p>
    <h3>Producenti</h3>
    <p>Louis D'Esposito</p>
    <p>Victoria Alonso</p>
    <p>Jon Favreau</p>
    <p>Stan Lee</p>
    <img src="img/marvel10y.jpg" alt="Marvel 10 let foto" class="deset">
    <footer>
        <ul class="odkaz">
            <li>Matěj Bartusek, m.bartusek.st@spseiostrava<a href="img/tf.jpg" target="_blank">.</a>cz, 13. 6. 2022</li>
        </ul>
    </footer>
</body>

</html>