<!DOCTYPE html>

<html lang="cs-cz">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/jpg" href="img/mcu.ico" />
    <link rel="stylesheet" href="style/style.css">
    <link rel="stylesheet" href="style/header.css">
    <title>MCU</title>
</head>

<body>
    <form method="POST">
        <label for="name">Uživatelské jméno: </label>
        <input type="text" name="name" id="name">
        <label for="password">Heslo: </label>
        <input type="password" name="password" id="password">
        <input type="submit" value="Přihlásit se">
    </form>
</body>

</html>