<!DOCTYPE html>
<?php 
session_start();
?>
<html lang="cs-cz">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/jpg" href="img/mcu.ico" />
    <link rel="stylesheet" href="style/novinky.css">
    <link rel="stylesheet" href="style/header.css">
    <title>NOVINKY</title>
</head>

<body>
    <?php require ("./view/header.phtml");?>
    <div class="obsah">
        <div class="fatws">
            <div class="wrapper">
                <h2>The Falcon and The Winter Soldier</h2>
                <p id="fatws">
                    The Falcon and The Winter Soldier je seriál, <br>ve kterém se bývalí parťáci Kapitána Ameriky Sam
                    Wilson a Bucky Barnes <br>vydávají po událostech Avengers: Endgame na nové dobrodružství. <br>Musí
                    chytit skupinu nových supervojáků, <br>kteří chtějí zrušit hranice států a vrátit svět do stavu jaký
                    byl během 5 let, <br>kdy byla polovina všeho živého zabita.
                </p>
            </div>
        </div>
        <div class="wv">
            <div class="wrapper2">
                <h2>WandaVision</h2>
                <p id="wv">
                    Wanda Maximoff se po Avengers: Endgame odebrala do klidného městečka West View v New Jersey, <br>kde
                    si vytvořila svoji realitu a "vzala" si celé město jako rukojmí. <br>Žila si idilycký život, dokud
                    ji nevyrušilo něco z "venku".
                </p>
            </div>
        </div>
        <div class="ffh">
            <div class="wrapper3">
                <h2>Spider-Man: Far From Home</h2>
                <p id="ffh">
                    Když Iron Man luskl na konci Avengers: Endgame a zemřel, svět se ptá kdo bude nový Iron Man. <br>A
                    protože byl Tony Stark pro Spider-Mana něco jako mentor, tak si hodně lidí myslí, že to bude právě
                    on. <br>Peter se, ale necítí na to být nový Iron Man a předá jedinou věc, kterou mu Tony odkázal -
                    brýle E.D.I.T.H., <br>Quentinu Beckovi. Quentin Beck se vydává za muže z paralelního vesmíru. <br>Ve
                    skutečnosti se skupinou
                    lidí vytvořili plán na to jak zabít Petera a stát se novým Iron Manem.
                </p>
            </div>
        </div>
        <div class="endgame">
            <div class="wrapper4">
                <h2>Avengers: Endgame</h2>
                <p id="endgame">
                    Pět let po těžké porážce v Avengers: Infinity War se 6 originálních Avengerů se Scottem Langem
                    vydají na záchranu vesmíru. <br>Skrz Quantum Realm se jim povede cestovat časem a znovu získat
                    kameny
                    nekonečna. <br>Jakmile se vrátí zpátky do přítomnosti a přivedou všechny zpátky, <br>dostane se tam
                    i Thanos
                    z minulosti a vypukne epická bitva.
                </p>
            </div>
        </div>
    </div>
    <footer>
        <ul class="odkaz">
            <li>Matěj Bartusek, m.bartusek.st@spseiostrava<a href="img/tf.jpg" target="_blank">.</a>cz, 13. 6. 2022</li>
        </ul>
        <ul class="odkaz">
            <li><a href="#top">ZPÁTKY NAHORU</a></li>
        </ul>
    </footer>
</body>

</html>