<!DOCTYPE html>

<html lang="cs-cz">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/jpg" href="img/mcu.ico" />
    <link rel="stylesheet" href="style/header.css">
    <title>REGISTRACE</title>
</head>

<body>
    <header>
        <img src="img/LOGO1.png" alt="logo studia" class="logo">
    </header>
    <form method="POST">
        <label for="email">E-mail: </label>
        <input type="text" name="email" id="email">
        <label for="name">Uživatelské jméno: </label>
        <input type="text" name="name" id="name">
        <label for="password">Heslo: </label>
        <input type="password" name="password" id="password">
        <input type="submit" value="Registrovat">
    </form>
    <footer>
        <ul class="odkaz">
            <li>Matěj Bartusek, m.bartusek.st@spseiostrava<a href="img/tf.jpg" target="_blank">.</a>cz, 13. 6. 2022</li>
        </ul>
    </footer>
</body>

</html>