<!DOCTYPE html>
<?php 
session_start();
?>
<html lang="cs-cz">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/jpg" href="img/mcu.ico" />
    <link rel="stylesheet" href="style/socialni_site.css">
    <link rel="stylesheet" href="style/header.css">
    <title>SOCIÁLNÍ SÍTĚ</title>
</head>

<body>
    <?php require ("./view/header.phtml");?>
    <section>
        <div class="stred">
            <div class="ig">
                <img src="img/ig.png" alt="instagram">
                <a href="https://www.instagram.com/marvelstudios/" target="_blank">@marvelstudios
                </a>
            </div>
            <div class="fb">
                <img src="img/fb.png" alt="facebook">
                <a href="https://www.facebook.com/marvelstudios" target="_blank">Marvel Studios
                </a>
            </div>
            <div class="tw">
                <img src="img/tw.png" alt="twitter">
                <a href="https://twitter.com/marvelstudios?lang=cs" target="_blank">@MarvelStudios
                </a>
            </div>
        </div>
    </section>
    <footer>
        <ul class="odkaz">
            <li>Matěj Bartusek, m.bartusek.st@spseiostrava<a href="img/tf.jpg" target="_blank">.</a>cz, 13. 6. 2022</li>
        </ul>
    </footer>
</body>

</html>